[kiwoom.quant]
key_file = "investment_key/kiwoom.key"
order_file = "order/kiwoom/quant_order.xlsx"
mock = false

[kiwoom.test]
key_file = "investment_key/kiwoomtest.key"
order_file = "order/kiwoom/test_order.xlsx"
mock = true

[hantoo.quant]
key_file = "investment_key/koreainvestment.key"
order_file = "order/hantoo/quant_order.xlsx"
mock = false

[hantoo.test]
key_file = "investment_key/koreainvestmenttest.key"
order_file = "order/hantoo/test_order.xlsx"
mock = true
